name: Feature Request
description: Suggest an idea
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: what
    attributes:
      label: What should it do?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why do you want it?
      description: The problem it solves or the workflow it improves.
    validations:
      required: true
